// <auto-generated />
using CCL.Inventario.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CCL.Inventario.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622001704_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CCL.Inventario.Api.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("productos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 10,
                            Nombre = "Laptop Dell"
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 15,
                            Nombre = "Monitor Samsung"
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 25,
                            Nombre = "Teclado Logitech"
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 30,
                            Nombre = "Mouse Inalámbrico"
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 8,
                            Nombre = "Auriculares Sony"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
